trigger:
- none

pool:
  name: bara
  demands:
    - agent.name -equals vmagentm

steps:
- script: |
    # Set ANDROID_HOME environment variable
    export ANDROID_HOME=/home/azureuser/myagent/sdk
    export PATH=$PATH:$ANDROID_HOME/platform-tools:$ANDROID_HOME/cmdline-tools/latest/bin
    # Ensure Flutter is correctly set up
    /home/azureuser/myagent/sdk/flutter/bin/flutter --version
    # Check outdated packages
    /home/azureuser/myagent/sdk/flutter/bin/flutter pub outdated
    # Upgrade packages
    /home/azureuser/myagent/sdk/flutter/bin/flutter pub upgrade
    # Get dependencies
    /home/azureuser/myagent/sdk/flutter/bin/flutter pub get
  displayName: 'Run Flutter Commands'

- task: FlutterBuild@0
  inputs:
    target: 'apk'
    projectDirectory: './'
    flutterDirectory: '/home/azureuser/myagent/sdk/flutter/bin'
