trigger:
  - none

pool:
  name: bara
  demands:
    - agent.name -equals vmagentm

steps:
- script: 
    pwd
    
- script: |
    flutter --version
    flutter pub outdated
    flutter pub upgrade --major-versions
    flutter pub get
  displayName: 'Run Flutter Commands'

- task: FlutterBuild@0
  inputs:
    target: 'apk'
    projectDirectory: './'  # Ensure this points to your project
    flutterDirectory: '/home/azureuser/myagent/sdk/flutter/bin'
    
- script: 
    pwd
    
- script: |
      flutter pub get
      flutter test
  displayName: 'Install dependencies and run tests'

- task: PublishTestResults@2
  inputs:
      testResultsFiles: './test-results.xml'
      testResultsFormat: 'JUnit'