trigger:
- none

pool:
  name: bara
  demands:
    - agent.name -equals vmagentm

steps:
- script: 
      pwd
      

- task: FlutterBuild@0
  inputs:
    target: 'apk'
    projectDirectory: './'
    flutterDirectory: '/home/azureuser/myagent/sdk/flutter/bin'
