trigger:
- none

pool:
  name: bara
  demands:
    - agent.name -equals vmagentm

steps:
- script: |
    # Ensure Flutter is correctly set up
    /home/azureuser/myagent/sdk/flutter/bin/flutter --version
    # Check outdated packages
    /home/azureuser/myagent/sdk/flutter/bin/flutter pub outdated
    # Upgrade packages
    /home/azureuser/myagent/sdk/flutter/bin/flutter pub upgrade
    # Get dependencies
    /home/azureuser/myagent/sdk/flutter/bin/flutter pub get
  displayName: 'Run Flutter Commands'

- task: FlutterBuild@0
  inputs:
    target: 'apk'
    projectDirectory: './'
    flutterDirectory: '/home/azureuser/myagent/sdk/flutter/bin'