trigger:
- none

pool:
  name: bara
  demands:
    - agent.name -equals vmagentm

steps:
- script: 
      pwd
      flutter --version
- script: |
    
    flutter --version
  
    flutter pub outdated

    flutter pub upgrade --major-versions

    flutter pub get
  displayName: 'Run Flutter Commands'      

- task: FlutterBuild@0
  inputs:
    target: 'apk'
    projectDirectory: './'
    flutterDirectory: '/home/azureuser/myagent/sdk/flutter/bin'

- script: |
    ls -la ./    # List the contents of the directory to verify correct path
  displayName: 'List Directory Contents'
- task: FlutterTest@0
  inputs:
    projectDirectory: './'