trigger:
  - none

pool:
  name: bara
  demands:
    - agent.name -equals vmagentm

steps:
- script: 
    pwd
    
- script: |
    flutter --version
    flutter pub outdated
    flutter pub upgrade --major-versions
    flutter pub get
  displayName: 'Run Flutter Commands'

- task: FlutterBuild@0
  inputs:
    target: 'apk'
    projectDirectory: './'  # Ensure this points to your project
    flutterDirectory: '/home/azureuser/myagent/sdk/flutter/bin'
    
    
- script: |
      flutter test test/widget_test.dart
  displayName: 'Integration Test '

- script: |
      flutter pub get
      flutter pub run build_runner build
      flutter test test/register_controller_test.dart
      flutter test test/register_page_test.dart
  displayName: ' JUnit Test'
- script: |
    flutter test --machine > test-results.json
    cat test-results.json | tojunit > test-results.xml || true
  displayName: 'Create JUnit Test Results'

- task: PublishTestResults@2
  inputs:
    testResultsFiles: './test-results.xml'
    testResultsFormat: 'JUnit'
  
- script: |
      sonar-scanner \
      -Dsonar.projectKey=TunisairSonar \
      -Dsonar.sources=. \
      -Dsonar.host.url=http://51.120.245.174:9000 \
      -Dsonar.login=sqp_a47a048261e0a555394172c3300a49986f2cf3f8
  displayName: 'Run SonarQube Analysis'