trigger:
- none

pool:
  name: bara
  demands:
    - agent.name -equals vmagentm

steps:
- script: 
      pwd
      
- script: |
    # Ensure Flutter is correctly set up
    flutter --version
    # Check outdated packages
    flutter pub outdated
    # Upgrade packages
    flutter pub upgrade --major-versions
    # Get dependencies
    flutter pub get
  displayName: 'Run Flutter Commands'      

- task: FlutterBuild@0
  inputs:
    target: 'apk'
    projectDirectory: './'
    flutterDirectory: '/home/azureuser/myagent/sdk/flutter/bin'


- task: FlutterTest@0
  inputs:
    projectDirectory: './'